name: Android CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Publish ProtoHax to local Maven
      run: |
        git clone --recurse-submodules https://github.com/RohanDaCoder/ProtoHax.git
        cd ProtoHax
        ./gradlew publishToMavenLocal
        cd ..

    - name: Build ProtoHax-Android
      run: ./gradlew app:assembleDebug
